const shopActionTypes = {
    FETCHING_COLLECTIONS_START: 'FETCHING_COLLECTIONS_START',
    FETCHING_COLLECTIONS_SUCCESS: 'FETCHING_COLLECTIONS_SUCCESS',
    FETCHING_COLLECTIONS_FAILURE: 'FETCHING_COLLECTIONS_FAILURE'
};

export default shopActionTypes;