const checkoutActionTypes = {
    UPDATE_PROP: 'UPDATE_PROP',
    CALCULATE_SHIPPING_FEE_START: 'CALCULATE_SHIPPING_FEE_START',
    CALCULATE_SHIPPING_FEE_SUCCESS: 'CALCULATE_SHIPPING_FEE_SUCCESS',
    CALCULATE_SHIPPING_FEE_FAILED: 'CALCULATE_SHIPPING_FEE_FAILED',
    UPDATE_STEP: 'UPDATE_STEP'
};

export default checkoutActionTypes;